### PR TITLE
Process Payload with same keys as values with an Array

### PR DESCRIPTION
**Pull request by jantaylor**
The OpenToken RFC encoding allows for Arrays in the payload. However the current implementation of node-opentoken does not.
Currently, an open token is decrypted and it's payload is decoded as multiple lines with `key=value` pairs, which `node-opentoken` converts to a javascript object. 
The issue is: payloads having the same key, will get overwritten by the next line with the same key.
Example: A payload with the same key.

```zsh
# ...
node=boron
node=carbon
# ...
```
Becomes:
```js
{
  // ...
  node: "carbon",
  // ...
}
```

This PR's goal is to allow payload processing of same key values by adding them to an array.

```zsh
# ...
node=boron
node=carbon
# ...
```
Which then becomes:
```js
{
  // ...
  node: ["boron", "carbon"]
  // ...
}
```

### CODE REVIEW

**Comment by 73rhodes** [comment]
Thanks for the PR, sorry for the long radio silence. Using an internal code repo for most work these days.

**Comment by jantaylor** [comment]
Not a problem. Thanks @73rhodes!

**Comment by 73rhodes** [comment]
```
opentoken@1.1.0 | ISC | deps: none | versions: 14
OpenToken support for Node.JS
https://github.com/73rhodes/node-opentoken

dist
.tarball https://npm.metrics.ca/opentoken/-/opentoken-1.1.0.tgz
.shasum: ad49c465f5a5539d36f024bb6c898ee6f3ce2bd8
.integrity: sha512-uwiZhwKyg2rgT8pR9aKc8wRuSysKF5miPtkm9jmrwk2w/E5Uj8OkhY6kxsc2MhTcXpSS7nzr2iAkkDTJqo/7Ag==

dist-tags:
latest: 1.1.0

published 3 days ago by undefined <undefined>
```

**Comment by 73rhodes** [comment]
Sorry, I published it accidentally to a private repo; it's up on npmjs.org now.

**Pull request merged**
